### ISSUE TITLE
[FR?] change notes without firing a note on?

### ISSUE THREAD

**Issue by ajboni** [xaviergodart/sektron#3]
Hello, first of all  thanks for this AMAZING project! 
was looking for something with  "elektron-ish"  and this its perfect!

My main issue is when trying to set up a sequence if I use the arrow key to change the note value, it will trigger a sound o each value.

I have some minor "first-user"  feedback if you are interested as well.

**Comment by xaviergodart** [comment]
Thanks for your feedback!

My reasoning for this was that I wanted to be able to "preview" the note while setting up a sequence. I personally need to hear the note to know if it's the correct one :)
Is this a problem for you when the sequencer is paused as well? or only when playing?

How would you imagine this to work? Adding a global option to disable the preview or something like that?

And of course, I'm always open for more feedback!

**Comment by ajboni** [comment]
Hmm, maybe an option/shortcut to disable the preview when playing would be great.  I agree previewing the note is useful for certain cases (searching for a drum sound for example). 

On the other hand, in my use case (live jamming) , It can 'ruin' the jam (imagine a chromatic instrument). I don' think it will be an issue while the sequencer is paused to be honest.

I will spend some days with it and I tried to leave constructive feedback, I think this can be a really nice companion for a small hardware setup

**Comment by xaviergodart** [comment]
I just pushed a new version [v0.1.2](https://github.com/xaviergodart/sektron/releases/tag/v0.1.2) that disable the note preview while playing. You're right, it makes no sense and it can ruin the performance. I kept the preview active when the sequencer is paused.

Does that work for you?

> I will spend some days with it and I tried to leave constructive feedback, I think this can be a really nice companion for a small hardware setup

Thanks a lot :pray:

**Comment by ajboni** [comment]
> 
> Does that work for you?
> 

Works like a charm, thanks!!
