### ISSUE TITLE
Feedback and test features

### ISSUE THREAD

**Issue by ajboni** [xaviergodart/sektron#5]
Hello Again!

Been playing a bit with sektron, on a rpi with a 5" touchscreen and a bluetooth keyboard connected to 4 volcas.
The experience is quite nice! and I see a lot of potential in this project! 

Some feedback / wishlist / ideas that popped while jamming with this:

- Pattern direction: ability to set up the pattern play direction (forward/backwards/ping-pong).

- Modifying more than one step at a time. I know this might be difficult (and probably cumbersome), but it gets a bit annoying when trying to modify a few steps.(example: modifying velocity on hi hats on steps 1,4,8,12. My 'solution' is to [add a copy/paste mechanism. ](https://github.com/ajboni/sektron/commit/2d3b4d9f9a11c3964f7e629d08955a425a04980d) This improves productivity by a lot!  had to remap ctrl+c to ctr+q

- At first, I loved the idea of one key for each step. But In practice I  always tried to use the arrow keys to navigate to the next step. I added a [PrevStep/SextStep keymap](https://github.com/ajboni/sektron/commit/f515848986ea155154d4c5d7ded549881195b288), and (for me at least) was a nice booster, specially for copy pasting. This could potentially extremely useful for making a handheld/portable setup with fewer buttons.

- This is totally related to my setup, but allowing click (touch in my case) to select a step would be really nice. I didn't investigate further but the UI library might have mouse support. Similarly touch/click and drag parameter could be another good usecase.

- MIDI input would be killer, either in a step mode or in a live recording situation. I'm unaware of the complexities though.

-  In digitakt, when in 'track mode' pressing a button would trigger  the  associated sound/midi note. Maybe there is a good way to implement this (ctrl + step index key ?). Also this could be useful for a potential "live record" feature.

- Polyphony: Digitakt does this by 'extending' the step note. only 4 notes supported. Not sure it is the best implementation but its something... I saw in the code some stuff about chords, so you might have already thought about that...

- We need Swing support!!

- LFO as you mentioned in the readme could be nice.

I was able to fork and setup a dev env pretty quick  and try a few features, I can open a PR for the mentioned features if you are interested but bear in mind is my first time with golang (hugo counts?) so the code might need some review.

Again, this is fantastic, thanks and good job!

**Comment by xaviergodart** [comment]
Your feedback is awesome, thank you very much for the effort!
Would you mind creating a separate issues for each point? I know it's a pain but it will increase readability.


>    Pattern direction: ability to set up the pattern play direction (forward/backwards/ping-pong)

This would be a cool feature. It should be pretty easy to implement. For now, I would like to refrain from adding new sequencer parameters until we get the rest of the workflow right. The parameters part of the code is kind of clunky, so I may rewrite it at some point.


>    Modifying more than one step at a time. I know this might be difficult (and probably cumbersome), but it gets a bit annoying when trying to modify a few steps.(example: modifying velocity on hi hats on steps 1,4,8,12. My 'solution' is to [add a copy/paste mechanism. ](https://github.com/ajboni/sektron/commit/2d3b4d9f9a11c3964f7e629d08955a425a04980d) This improves productivity by a lot!  had to remap ctrl+c to ctr+q

Super interested by this! Feel free to open a PR.


>    At first, I loved the idea of one key for each step. But In practice I  always tried to use the arrow keys to navigate to the next step. I added a [PrevStep/SextStep keymap](https://github.com/ajboni/sektron/commit/f515848986ea155154d4c5d7ded549881195b288), and (for me at least) was a nice booster, specially for copy pasting. This could potentially extremely useful for making a handheld/portable setup with fewer buttons.

Interesting. Feel free to submit a PR too. It seems weird to me to have multiple ways of selecting a step, but I can see how it would work with the copy/paste feature. I will try that.


>    This is totally related to my setup, but allowing click (touch in my case) to select a step would be really nice. I didn't investigate further but the UI library might have mouse support. Similarly touch/click and drag parameter could be another good usecase.

There's mouse support with bubbletea so it should be doable. And I can see the interest with touchscreens.

 
>    MIDI input would be killer, either in a step mode or in a live recording situation. I'm unaware of the complexities though.

We can listen to midi in without issues. There will be some concurrency issues in a live recording situation though (reading and writing steps at the same time) so we would need to add some mutexes on steps data.
Do you use step recording on the digitakt? I own a syntakt, and I only use the live recording mode. Step mode has always seemed weird to me.


>    In digitakt, when in 'track mode' pressing a button would trigger  the  associated sound/midi note. Maybe there is a good way to implement this (ctrl + step index key ?). Also this could be useful for a potential "live record" feature.

Maybe ctrl+track key? Seems clunky though, especially for recording. This would need some experimenting.


>    Polyphony: Digitakt does this by 'extending' the step note. only 4 notes supported. Not sure it is the best implementation but its something... I saw in the code some stuff about chords, so you might have already thought about that...

Yeah, I always though I would add some polyphony support, so all the data structures are ready. The main issue is how to add that nicely in the UI. Right now I don't have a nice solution in mind.
One easy solution would be to implement something like the chord machine in the syntakt or model:cycles. It's kind of rigid, but easy to reason about in terms of UI/UX.


>    We need Swing support!!

You can already make it swing with the offset parameter! But It's tedious, a track swing parameter would be better.


>    LFO as you mentioned in the readme could be nice.

Yes, and another thing that goes with that is trigger-less steps. That would allow to control only midi cc messages.

> I was able to fork and setup a dev env pretty quick and try a few features, I can open a PR for the mentioned features if you are interested but bear in mind is my first time with golang (hugo counts?) so the code might need some review.

No worries! I'm open to all contribution.

**Comment by ajboni** [comment]
Thanks for the replies! created each individual issue.
